/* Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence 
whose values do not exceed four million, find the sum of the even-valued terms. 
Analysis: 
term1 & term2 store consecutive terms of the Fibonacci sequence. 
Test both variables with the modulo function
If even store in variable called sum. 
Let a new variable term0 be term2, term2 be sum of term 1 and term2, term1 be term 0
Repeat until limit 

*/
var term0 = 0;
var term1 = 1;
var term2 = 2;
var sum = 0;

while (term1 < 4000000) {
	if ((term1 % 2) === 0) {
		sum += term1;
	}
	term0 = term2;
	term2 += term1;
	term1 = term0;
}

console.log(sum);